# Generated by Django 5.2.16 on 2026-07-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BridgeAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("requester_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("endpoint", models.CharField(max_length=255)),
                ("response_code", models.IntegerField()),
                (
                    "data_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON body returned to the requester.",
                    ),
                ),
            ],
            options={
                "db_table": "bridge_access_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="bridge_acce_timesta_d2b27c_idx"
                    ),
                    models.Index(
                        fields=["endpoint", "-timestamp"],
                        name="bridge_acce_endpoin_09cfe5_idx",
                    ),
                ],
            },
        ),
    ]
