# Generated by Django 5.2.16 on 2026-07-23 18:19

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bridge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bridgeaccesslog",
            name="data_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="JSON body returned to the requester.",
            ),
        ),
    ]
