# Generated by Django 5.2.16 on 2026-07-23 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "plan_interval",
                    models.CharField(
                        blank=True,
                        choices=[("monthly", "Mensal"), ("annual", "Anual")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
