# Generated by Django 5.2.16 on 2026-07-23 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "discount_percent",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("uses_count", models.PositiveIntegerField(default=0)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
