# Generated by Django 5.2.16 on 2026-07-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("operator", "Operator"),
                    ("viewer", "Viewer"),
                    ("customer", "Customer"),
                ],
                default="viewer",
                max_length=20,
            ),
        ),
    ]
