# Generated by Django 5.2.16 on 2026-07-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fill',
            new_name='wallets_fil_wallet__e920e1_idx',
            old_name='wallets_fill_wallet_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='fill',
            new_name='wallets_fil_wallet__923810_idx',
            old_name='wallets_fill_wallet_asset_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='position',
            new_name='wallets_pos_wallet__426524_idx',
            old_name='wallets_position_wallet_status_idx',
        ),
        migrations.RenameIndex(
            model_name='position',
            new_name='wallets_pos_wallet__32721d_idx',
            old_name='wallets_position_wallet_asset_status_idx',
        ),
        migrations.RenameIndex(
            model_name='wallet',
            new_name='wallets_wal_is_targ_e8c8fa_idx',
            old_name='wallets_wallet_target_active_idx',
        ),
        migrations.AlterField(
            model_name='fill',
            name='oid',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='fill',
            index=models.Index(fields=['oid'], name='fill_oid_idx'),
        ),
    ]
