# Generated by Django 5.2.16 on 2026-07-20 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_timescaledb_hypertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletMetricsWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('window', models.CharField(choices=[('24h', '24 Hours'), ('7d', '7 Days'), ('30d', '30 Days'), ('90d', '90 Days'), ('180d', '180 Days')], db_index=True, max_length=5)),
                ('computed_at', models.DateTimeField(db_index=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('total_pnl', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('total_fees', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('account_value', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('normalized_pnl', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('max_drawdown', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('max_drawdown_pct', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('current_drawdown_pct', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('daily_returns_std', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('avg_notional_ratio', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('notional_ratio_std', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('martingale_severity', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('martingale_events', models.IntegerField(default=0)),
                ('assets_total_count', models.IntegerField(default=0)),
                ('assets_positive_count', models.IntegerField(default=0)),
                ('asset_pnl_json', models.JSONField(blank=True, default=dict)),
                ('regime_pnl_json', models.JSONField(blank=True, default=dict)),
                ('daily_returns_json', models.JSONField(blank=True, default=list)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_windows', to='wallets.wallet')),
            ],
            options={
                'db_table': 'wallets_metrics_window',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('window', models.CharField(choices=[('24h', '24 Hours'), ('7d', '7 Days'), ('30d', '30 Days'), ('90d', '90 Days'), ('180d', '180 Days')], db_index=True, max_length=5)),
                ('computed_at', models.DateTimeField(db_index=True)),
                ('score_raw', models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('classification', models.CharField(choices=[('fraco', 'Fraco'), ('mediano', 'Mediano'), ('bom', 'Bom'), ('elite', 'Elite')], db_index=True, default='fraco', max_length=10)),
                ('component_breakdown', models.JSONField(blank=True, default=dict)),
                ('rank', models.IntegerField(blank=True, db_index=True, null=True)),
                ('metrics_window', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score', to='wallets.walletmetricswindow')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='wallets.wallet')),
            ],
            options={
                'db_table': 'wallets_score',
                'ordering': ['-score_raw'],
            },
        ),
        migrations.AddIndex(
            model_name='walletmetricswindow',
            index=models.Index(fields=['window', 'computed_at'], name='wallets_met_window_c18c8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='walletmetricswindow',
            unique_together={('wallet', 'window')},
        ),
        migrations.AddIndex(
            model_name='walletscore',
            index=models.Index(fields=['window', '-score_raw'], name='wallets_sco_window_fbf611_idx'),
        ),
        migrations.AddIndex(
            model_name='walletscore',
            index=models.Index(fields=['classification', 'window'], name='wallets_sco_classif_d57509_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='walletscore',
            unique_together={('wallet', 'window')},
        ),
    ]
