# Generated by Django 5.2.16 on 2026-07-20 16:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallets", "0006_tracking_promotion_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("new_position", "New position opened"),
                            ("position_closed", "Position closed/reduced"),
                            ("score_threshold_cross", "Score crossed threshold"),
                            ("convergence", "Smart-money convergence"),
                            ("asset_specific", "Asset-specific filter"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "asset_filter",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("interface", "Interface"),
                            ("both", "Telegram + Interface"),
                        ],
                        default="both",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "alertsalertrule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=8,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=32)),
                ("read", models.BooleanField(db_index=True, default=False)),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "alert_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="alerts.alertrule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "alertsnotification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(db_index=True, max_length=32)),
                (
                    "asset",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                ("fired_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_history",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "alert_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="alerts.alertrule",
                    ),
                ),
                (
                    "notification",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_entry",
                        to="alerts.notification",
                    ),
                ),
            ],
            options={
                "db_table": "alertshistory",
                "ordering": ["-fired_at"],
            },
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["is_active", "condition_type"],
                name="alertsalert_is_acti_3cdc71_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["wallet", "is_active"], name="alertsalert_wallet__921d26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "read", "created_at"],
                name="alertsnotif_user_id_6c2f13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["sent_at"], name="alertsnotif_sent_at_92be1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerthistory",
            index=models.Index(
                fields=["alert_rule", "wallet", "event_type", "fired_at"],
                name="alertshisto_alert_r_a1d5bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alerthistory",
            index=models.Index(
                fields=["-fired_at"], name="alertshisto_fired_a_8bc151_idx"
            ),
        ),
    ]
