# Generated by Django 5.2.16 on 2026-07-20 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallets", "0006_tracking_promotion_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CopyTradingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=10,
                        default=10000,
                        max_digits=30,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("conservative", "Conservative"),
                            ("moderate", "Moderate"),
                            ("aggressive", "Aggressive"),
                        ],
                        db_index=True,
                        default="moderate",
                        max_length=12,
                    ),
                ),
                (
                    "max_position_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=10,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_concurrent_positions",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "max_hold_hours",
                    models.IntegerField(
                        default=168,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copy_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "copytrading_profile",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CopyTradingTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=25,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="copytrading.copytradingprofile",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copy_targets",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "copytrading_target",
            },
        ),
        migrations.CreateModel(
            name="SimulatedTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset", models.CharField(db_index=True, max_length=20)),
                (
                    "side",
                    models.CharField(
                        choices=[("long", "Long"), ("short", "Short")],
                        db_index=True,
                        max_length=5,
                    ),
                ),
                ("entry_price", models.DecimalField(decimal_places=10, max_digits=30)),
                ("size_usd", models.DecimalField(decimal_places=10, max_digits=30)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                (
                    "pnl_usd",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                ("opened_at", models.DateTimeField(db_index=True)),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("liquidated", "Liquidated"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "fill_source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulated_trades",
                        to="wallets.fill",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="copytrading.copytradingprofile",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulated_trades",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "copytrading_trade",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.AddIndex(
            model_name="copytradingprofile",
            index=models.Index(
                fields=["user", "is_active"], name="copytrading_user_id_de4521_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="copytradingprofile",
            index=models.Index(
                fields=["is_active"], name="copytrading_is_acti_11f23d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="copytradingtarget",
            index=models.Index(
                fields=["profile", "is_active"], name="copytrading_profile_fccc54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="copytradingtarget",
            index=models.Index(
                fields=["wallet", "is_active"], name="copytrading_wallet__aa853c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="copytradingtarget",
            unique_together={("profile", "wallet")},
        ),
        migrations.AddIndex(
            model_name="simulatedtrade",
            index=models.Index(
                fields=["profile", "status"], name="copytrading_profile_17e71a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulatedtrade",
            index=models.Index(
                fields=["profile", "wallet", "status"],
                name="copytrading_profile_54ac26_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="simulatedtrade",
            index=models.Index(
                fields=["wallet", "asset", "status"],
                name="copytrading_wallet__60a7df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="simulatedtrade",
            index=models.Index(
                fields=["opened_at"], name="copytrading_opened__eb2d32_idx"
            ),
        ),
    ]
